import pathlib, glob

versions_dir = pathlib.Path('/app/app/db/migrations/versions')
files = sorted(versions_dir.glob('*.py'))
if not files:
    print('no migration files found')
    exit(1)

f = files[0]
txt = f.read_text()

ext_sql = 'op.execute("CREATE EXTENSION IF NOT EXISTS vector")'
if ext_sql not in txt:
    marker = '    # ### commands auto generated by Alembic - please adjust! ###\n'
    replacement = marker + '    ' + ext_sql + '\n'
    txt = txt.replace(marker, replacement, 1)
    f.write_text(txt)
    print(f'patched {f.name}')
else:
    print('already patched')

# verify
idx = txt.find('op.execute')
print(txt[idx:idx+80])
